#!/bin/bash
export NODE_TLS_REJECT_UNAUTHORIZED=0
cd $FIELDDB_HOME/LexiconWebService

forever \
start \
-al $FIELDDB_HOME/logs/fielddblexicon.log \
-ao $FIELDDB_HOME/logs/fielddblexiconout.log \
-ae $FIELDDB_HOME/logs/fielddblexiconerr.log \
./bin/lexicon-web-service
