#!/bin/bash

cd $FIELDDB_HOME/LexiconWebService
export NODE_ENV=production

forever \
start \
-al $FIELDDB_HOME/logs/fielddblexicon.log \
-ao $FIELDDB_HOME/logs/fielddblexiconout.log \
-ae $FIELDDB_HOME/logs/fielddblexiconerr.log \
./bin/lexicon-web-service
